### ISSUE TITLE
R is sampled recursively in project function

### ISSUE THREAD

**Issue by jarvisc1** [reconhub/projections#11]
In the project function the R input is overwritten by sampling from R with replacement.

https://github.com/reconhub/projections/blob/aa4ef8ce71df2c931f95a704aae13b4aa28699f5/R/project.R#L191-L198

For a small number of simulations this would mean we loose the diversity of R values. 

For example: If we had 1,000 R values and then do 3 simulations then on the second iteration we will sample from a maximum of 3 R values and then this will stay the same or reduce over each timestamp. 

To resolve change the name of of the sampled values to R_sim or R_samp and then it will be overwritten by the original R object in each iteration.

**Comment by zkamvar** [comment]
This is a very good point! I'll propose a patch.

**Comment by zkamvar** [comment]
Unfortunately, it's not going to be a quick fix... tests are currently failing for a couple of reasons:

1. the sampling bug fix in R 3.6
2. no one merged #9 
3. *someone* pushed failing code to master
