### ISSUE TITLE
Add tests for negbin model

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/projections#16]
This is currently untested. @sangeetabhatia03 I think you added this feature. Could you add unit tests?

**Comment by thibautjombart** [comment]
@sangeetabhatia03 some poke on this: could you check the current state of testing for the negbin model?

**Comment by sangeetabhatia03** [comment]
Hi Thibaut, sorry I should have replied earlier. A bit busy at the moment (as I am sure we all are!), I'll try to get to it in the next 1 month? If it is time critical, can we perhaps ask someone else to do it?

**Comment by thibautjombart** [comment]
Thanks for the quick reply. We'll try to find someone else to help on this.
