### ISSUE TITLE
How use the interval >1 to project the new values

### ISSUE THREAD

**Issue by jamesjin63** [reconhub/projections#23]
when using project(),  daily incidence needed, but interval is 2 days
are showing an Error;

`pred <- project(i, R = R0, si = si, n_days = 30, n_sim = 1000)
Error in project(i, R = R0, si = si, n_days = 30, n_sim = 1000) : 
  daily incidence needed, but interval is 2 days`

**Comment by thibautjombart** [comment]
Hi there, 
it is normal if your `incidence` object is indeed on 2 days interval. Branching processes as defined in the function require daily case counts and serial interval defined by days.
