### ISSUE TITLE
str() does not work with projections object

### ISSUE THREAD

**Issue by tjtnew** [reconhub/projections#27]
I thought this was fixed by #25 but apparently not.  Currently `str` errors if called on a projections object.  This seems to be due `str` trying to subset with a logical matrix which the current implementation of `[.projections` does not allow for.  Simple fix is to implement a `str.projections` method.  What I'm not sure on though is if this is highlighting something wrong with the `[.projections` implementation that has been overlooked.

**Comment by thibautjombart** [comment]
I will be on the move today (no computer). Thanks for looking into this.
Could it be a mismatch in the signature of the projection method compared
to its generic? Eg I'm not sure what 'drop = TRUE' does ..

// sent from my Armor5 phone

**Comment by tjtnew** [comment]
I'll have a look.  I had a little play with the signature last night but it's slightly complicated by the fact that `[` is primitive so I'm not sure if it behaves a little differently to other generics.

**Comment by tjtnew** [comment]
Update: I don't think there is any underlying issue that we're missing.  The answer just depends on whether we want `[` to be as flexible for projection objects as it is for matrices (e.g. Allow things like x[], x[a], indexing by matrices ...).  If so it is a little more complicated and may want s4.  Alternatively if we're happy with the current x[i,j] subsetting then the simplest solution is to define `str.projections`.  My inclination is the latter.  If someone needed any additional matrix like behaviour they can already call `as.matrix` and go from there.  If you agree I'll make a PR for `str.projections`.

**Comment by tjtnew** [comment]
This does seem to be fixed in the latest release.
