### ISSUE TITLE
use of isFALSE implies dependency on R 3.5

### ISSUE THREAD

**Issue by richfitz** [reconhub/projections#6]
This is causing me some issues.  The solutions are:

- require R (>= 3.5) in the DESCRIPTION (but please don't do that because that will cause me even more issues)
- import isFALSE from `backports`
- implement isFALSE in the package itself (`is.logical(x) && length(x) == 1L && !is.na(x) && !x`) or for the use that you have you can get away with `identical(as.vector(x), FALSE)`

**Comment by thibautjombart** [comment]
Sorry, I can't check your PR, I get:
"Sorry, this diff is temporarily unavailable due to heavy server load."
Agreed re deps; I will implement it in the package itself as an internal function

**Comment by thibautjombart** [comment]
Fixed via bc9fe613fda33564ee8bd87f03db18674dbe6931

**Comment by thibautjombart** [comment]
Note that `incidence` had the same issue, which got fixed via: bc9fe613fda33564ee8bd87f03db18674dbe6931

**Comment by richfitz** [comment]
Thanks dude!
